project:
  type: website

website:
  title: "Thoughtful AI Tools Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: pubs.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



