project:
  type: website

website:
  title: "Thoughtful AI Tools Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: senior_projects.qmd
        text: Senior Projects
      - href: pubs.qmd
        text: Publications
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



